ipinfo:
  request:
    url: 'https://ipinfo.io'
    get:
      token: '{your ipinfo token}'
tokoro:
  address:
    # 住所を入力　以下は例
    home: '自宅の住所'
    company: '会社の住所'
openweathermap:
  request:
    url: 'http://api.openweathermap.org/data/2.5/forecast'
    get:
      appID: '{your api key}'
      cnt: '35'
      units: 'metric'
      mode: 'json'
